### ISSUE TITLE
macOS - Termination Reason:  DYLD, [0x1] Library missing

### ISSUE THREAD

**Issue by selsrog** [monacocoin-net/monoeci-core-OLD#13]
Hi,

got this DYLD problem.
Tried following fixes (internet searches...). Non of them solved the issue.

reinstall iTunes, 
install XCode. 
brew install libusb, brew doctor, brew prune, ...

Installed it on another machine (MacBook, earlier on it was an iMac), same problem.

Any ideas?

Cheers,
—Roger 

===
Process:               Monoeci-Qt [8857]
Path:                  /Applications/Monoeci-Qt.app/Contents/MacOS/Monoeci-Qt
Identifier:            org.monoeci.Monoeci-Qt
Version:               0.12.2 (0.12.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Monoeci-Qt [8857]
User ID:               501

Date/Time:             2018-05-19 15:45:40.608 +0200
OS Version:            Mac OS X 10.13.4 (17E202)
Report Version:        12
Anonymous UUID:        E0579DD3-BB0E-E601-D319-7391BF0E5A35

Time Awake Since Boot: 5500 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/Monoeci-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x107598000 -        0x108228fff +org.monoeci.Monoeci-Qt (0.12.2 - 0.12.2) <0B07715A-3A58-3ED3-97BE-22FFC594BC65> /Applications/Monoeci-Qt.app/Contents/MacOS/Monoeci-Qt
       0x108350000 -        0x1083a3ff7 +libzmq.5.dylib (0) <F7B973DE-A175-361A-8131-334BCDCF6BB4> /Applications/Monoeci-Qt.app/Contents/Frameworks/libzmq.5.dylib
       0x1083b3000 -        0x1083b5ff7 +libboost_system.dylib (0) <D72B83E6-527A-30C8-A767-CF658E84FBAC> /Applications/Monoeci-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x1083b9000 -        0x1083c8ff7 +libboost_filesystem.dylib (0) <7EB22425-F98A-3200-8C76-512946198C83> /Applications/Monoeci-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x1083d1000 -        0x1083d2fff +libevent_pthreads-2.1.6.dylib (0) <32AC3368-70B7-32B4-8465-50FA643C2649> /Applications/Monoeci-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.6.dylib
       0x1083d8000 -        0x108409fff +libboost_program_options-mt.dylib (0) <ECEECCE3-7ABA-3758-BBB4-1D47C3560F8F> /Applications/Monoeci-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x10842a000 -        0x108437fff +libboost_thread-mt.dylib (0) <40ED37AC-99FD-3039-AB13-B3ACB21DB32F> /Applications/Monoeci-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x108441000 -        0x108442ffb +libboost_chrono-mt.dylib (0) <224627E3-7526-3794-A091-16E67D877742> /Applications/Monoeci-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x108448000 -        0x10854fff7 +QtNetwork (5.5.1) <883A53FB-7857-34BC-B732-F23592EA3B26> /Applications/Monoeci-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10858c000 -        0x108a83ff7 +QtWidgets (5.5.1) <51985D53-4933-38E5-A842-DC85D15F5F8C> /Applications/Monoeci-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x108bb9000 -        0x108c1bff7 +QtDBus (5.5.1) <27A55C14-E871-3DBE-8538-87D711FFAB35> /Applications/Monoeci-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x108c30000 -        0x108d56ff3 +libprotobuf.14.dylib (0) <FAA23550-6459-3B0B-9053-0491A24DA85F> /Applications/Monoeci-Qt.app/Contents/Frameworks/libprotobuf.14.dylib
       0x108dfc000 -        0x108e04ff3 +libminiupnpc.16.dylib (0) <FD041313-B0A5-3A91-B905-4FF19CB15D04> /Applications/Monoeci-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x108e08000 -        0x108e34ff7 +libevent-2.1.6.dylib (0) <B4866E97-7CC4-3E15-BF2C-F667971CE7C7> /Applications/Monoeci-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x108e51000 -        0x108e9b9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
       0x108eef000 -        0x109381ff7 +QtGui (5.5.1) <5C681010-C0B3-36D9-BD77-3BDC232EF97F> /Applications/Monoeci-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10945f000 -        0x10995eff7 +QtCore (5.5.1) <73946C22-5E05-3FD4-B5D5-B0DBCD039222> /Applications/Monoeci-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x1099eb000 -        0x109b05ff3 +libdb_cxx-4.8.dylib (0) <A961AAB6-ED4B-36F5-846E-F8B24D4FFFC8> /Applications/Monoeci-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x109b3d000 -        0x109b7efff +libssl.1.0.0.dylib (0) <CB91FB11-F59B-33C4-8D22-9E4917F6CF03> /Applications/Monoeci-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x109b9a000 -        0x109d0ac87 +libcrypto.1.0.0.dylib (0) <98FFE817-09E4-387B-B497-D4E74740AD0C> /Applications/Monoeci-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
    0x7fff286ee000 -     0x7fff2954cfff  com.apple.AppKit (6.9 - 1561.40.112) <C839B0C1-F7EE-3056-985C-63CF1A030EC4> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff2959e000 -     0x7fff2959efff  com.apple.ApplicationServices (48 - 50) <8DA47D38-B07B-3AE2-B343-4579864430C6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff2b10f000 -     0x7fff2b5b0fef  com.apple.CoreFoundation (6.9 - 1452.23) <945E5C0A-86C5-336E-A64F-5BF06E78985A> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff2c27b000 -     0x7fff2c27bfff  com.apple.CoreServices (822.31 - 822.31) <615919A2-AE11-3F27-9A37-FB0CFF8D36B6> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff2d263000 -     0x7fff2d629fff  com.apple.Foundation (6.9 - 1452.23) <E64540AD-1755-3C16-8537-552A00E92541> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff50c93000 -     0x7fff50cc6ff7  libclosured.dylib (551.3) <DC3DA678-9C40-339C-A9C6-32AB74FCC682> /usr/lib/closure/libclosured.dylib
    0x7fff511cd000 -     0x7fff511ceffb  libSystem.B.dylib (1252.50.4) <F64430FD-30A6-328D-A476-0AED41D371C6> /usr/lib/libSystem.B.dylib
    0x7fff51402000 -     0x7fff51458fff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff51459000 -     0x7fff5147dff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff5287c000 -     0x7fff52c6a7e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff53340000 -     0x7fff53344ff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff53345000 -     0x7fff5334fff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff53350000 -     0x7fff53357fff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff53358000 -     0x7fff53361ffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff53362000 -     0x7fff533e7fff  libcorecrypto.dylib (562.50.17) <67007279-24E1-3F30-802D-A55CD5C27946> /usr/lib/system/libcorecrypto.dylib
    0x7fff5346f000 -     0x7fff534a8ff7  libdispatch.dylib (913.50.12) <848EEE57-4235-3A61-9A52-C0097DD2AB5E> /usr/lib/system/libdispatch.dylib
    0x7fff534a9000 -     0x7fff534c6ff7  libdyld.dylib (551.3) <CF59A5A5-288B-30E6-BD42-9056B4E4139A> /usr/lib/system/libdyld.dylib
    0x7fff534c7000 -     0x7fff534c7ffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff534d5000 -     0x7fff534d5ff7  liblaunch.dylib (1205.50.76) <4D52BB64-C568-3A36-8935-2480427EE2A2> /usr/lib/system/liblaunch.dylib
    0x7fff534d6000 -     0x7fff534daffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff534db000 -     0x7fff534ddff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff534de000 -     0x7fff534dfff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff534e0000 -     0x7fff534f7fff  libsystem_asl.dylib (356.50.1) <3B24F2D1-B578-359D-ADB2-0ED19A364C38> /usr/lib/system/libsystem_asl.dylib
    0x7fff534f8000 -     0x7fff534f8fff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff534f9000 -     0x7fff53582ff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff53583000 -     0x7fff53586ffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff53587000 -     0x7fff5358affb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff5358b000 -     0x7fff5358cfff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff5358d000 -     0x7fff53593ff7  libsystem_dnssd.dylib (878.50.17) <9033B909-BCF7-37EB-A040-ADE8081611D6> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff53594000 -     0x7fff535ddff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff535de000 -     0x7fff53604ff7  libsystem_kernel.dylib (4570.51.2) <7FF1E390-2FAC-33A7-A545-60D9BB6692D4> /usr/lib/system/libsystem_kernel.dylib
    0x7fff53605000 -     0x7fff53650fcb  libsystem_m.dylib (3147.50.1) <FC2E58BA-E6D5-3D2A-89CA-67F212294136> /usr/lib/system/libsystem_m.dylib
    0x7fff53651000 -     0x7fff53670fff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff53671000 -     0x7fff537a1ff3  libsystem_network.dylib (1229.51.2) <F65ED095-8ABA-3355-93F8-B9D0505932F4> /usr/lib/system/libsystem_network.dylib
    0x7fff537a2000 -     0x7fff537acffb  libsystem_networkextension.dylib (767.50.25) <758F1414-796D-3422-83C9-92D2915A06CE> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff537ad000 -     0x7fff537b6ff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff537b7000 -     0x7fff537beff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff537bf000 -     0x7fff537cafff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff537cb000 -     0x7fff537cefff  libsystem_sandbox.dylib (765.50.51) <B48D256E-D7DB-3D4F-BC95-34557170C7AA> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff537cf000 -     0x7fff537d0ff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff537d1000 -     0x7fff537d8ff7  libsystem_symptoms.dylib (820.50.37) <ED7350E0-B68B-374A-9AB7-DC1F195A8327> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff537d9000 -     0x7fff537ecfff  libsystem_trace.dylib (829.50.17) <6568D68B-1D4C-38EE-90A9-54821D6403C0> /usr/lib/system/libsystem_trace.dylib
    0x7fff537ee000 -     0x7fff537f3ff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff537f4000 -     0x7fff53821fff  libxpc.dylib (1205.50.76) <25DB244E-217D-3CE0-A8F2-0C4255783B42> /usr/lib/system/libxpc.dylib

Model: iMac18,2, BootROM IM183.0157.B00, 4 processors, Intel Core i5, 3 GHz, 8 GB, SMC 2.40f0
Graphics: Radeon Pro 555, Radeon Pro 555, PCIe
Memory Module: BANK 0/DIMM0, 4 GB, DDR4, 2400 MHz, 0x80AD, 0x484D413835315336414652364E2D554820202020
Memory Module: BANK 1/DIMM0, 4 GB, DDR4, 2400 MHz, 0x80AD, 0x484D413835315336414652364E2D554820202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x16E), Broadcom BCM43xx 1.0 (7.77.37.29.1a7)
Bluetooth: Version 6.0.5f3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
USB Device: USB 3.0 Bus
USB Device: Magic Trackpad 2
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB Receiver
Thunderbolt Bus: iMac, Apple Inc., 33.1

**Comment by Yoyae** [comment]
I'm investigating this issue right now, I may have a fix very soon for you to test.

**Comment by hppoelstra** [comment]
Hi, 

Guessing I have the same issue....

Process:               monoeci-Qt [896]
Path:                  /Applications/monoeci-Qt.app/Contents/MacOS/monoeci-Qt
Identifier:            org.monoeci.monoeci-Qt
Version:               0.12.2 (0.12.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           monoeci-Qt [896]
User ID:               501

Date/Time:             2018-05-26 21:34:37.033 +0200
OS Version:            Mac OS X 10.13.4 (17E199)
Report Version:        12
Anonymous UUID:        282A5582-F183-1138-09CF-C95151864D3B


Time Awake Since Boot: 1000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/monoeci-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x10338c000 -        0x103e62ff7 +org.monoeci.monoeci-Qt (0.12.2 - 0.12.2) <4701A0E6-6D84-3982-9D52-1FFC28BBDF95> /Applications/monoeci-Qt.app/Contents/MacOS/monoeci-Qt
       0x103fa9000 -        0x103ffcff7 +libzmq.5.dylib (0) <F7B973DE-A175-361A-8131-334BCDCF6BB4> /Applications/monoeci-Qt.app/Contents/Frameworks/libzmq.5.dylib
       0x10400f000 -        0x104011ff7 +libboost_system.dylib (0) <D72B83E6-527A-30C8-A767-CF658E84FBAC> /Applications/monoeci-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x104018000 -        0x104027ff7 +libboost_filesystem.dylib (0) <7EB22425-F98A-3200-8C76-512946198C83> /Applications/monoeci-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x104036000 -        0x104067fff +libboost_program_options-mt.dylib (0) <ECEECCE3-7ABA-3758-BBB4-1D47C3560F8F> /Applications/monoeci-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x104086000 -        0x104093fff +libboost_thread-mt.dylib (0) <40ED37AC-99FD-3039-AB13-B3ACB21DB32F> /Applications/monoeci-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x1040a3000 -        0x1040a4ffb +libboost_chrono-mt.dylib (0) <224627E3-7526-3794-A091-16E67D877742> /Applications/monoeci-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x1040ac000 -        0x1041b3ff7 +QtNetwork (5.5.1) <883A53FB-7857-34BC-B732-F23592EA3B26> /Applications/monoeci-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x1041eb000 -        0x1046e2ff7 +QtWidgets (5.5.1) <51985D53-4933-38E5-A842-DC85D15F5F8C> /Applications/monoeci-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10481f000 -        0x104cb1ff7 +QtGui (5.5.1) <5C681010-C0B3-36D9-BD77-3BDC232EF97F> /Applications/monoeci-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x104d96000 -        0x105295ff7 +QtCore (5.5.1) <73946C22-5E05-3FD4-B5D5-B0DBCD039222> /Applications/monoeci-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x105328000 -        0x10538aff7 +QtDBus (5.5.1) <27A55C14-E871-3DBE-8538-87D711FFAB35> /Applications/monoeci-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x1053a6000 -        0x1054ccff3 +libprotobuf.14.dylib (0) <FAA23550-6459-3B0B-9053-0491A24DA85F> /Applications/monoeci-Qt.app/Contents/Frameworks/libprotobuf.14.dylib
       0x105578000 -        0x105692ff3 +libdb_cxx-4.8.dylib (0) <A961AAB6-ED4B-36F5-846E-F8B24D4FFFC8> /Applications/monoeci-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x1056cf000 -        0x105710fff +libssl.1.0.0.dylib (0) <A0B6C569-8EE4-35AA-880C-17E0A5CBDE97> /Applications/monoeci-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x10572e000 -        0x10589ec7f +libcrypto.1.0.0.dylib (0) <0220EA16-4B7D-30E9-8281-1AAC5A1965D8> /Applications/monoeci-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x105907000 -        0x10590fff3 +libminiupnpc.16.dylib (0) <FD041313-B0A5-3A91-B905-4FF19CB15D04> /Applications/monoeci-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x10591a000 -        0x10591bfff +libevent_pthreads-2.1.6.dylib (0) <32AC3368-70B7-32B4-8465-50FA643C2649> /Applications/monoeci-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.6.dylib
       0x105920000 -        0x10594cff7 +libevent-2.1.6.dylib (0) <B4866E97-7CC4-3E15-BF2C-F667971CE7C7> /Applications/monoeci-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x109c95000 -        0x109cdf9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
    0x7fff48ada000 -     0x7fff49938fff  com.apple.AppKit (6.9 - 1561.40.112) <C839B0C1-F7EE-3056-985C-63CF1A030EC4> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff4998a000 -     0x7fff4998afff  com.apple.ApplicationServices (48 - 50) <8DA47D38-B07B-3AE2-B343-4579864430C6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff4b4fb000 -     0x7fff4b99cfef  com.apple.CoreFoundation (6.9 - 1452.23) <945E5C0A-86C5-336E-A64F-5BF06E78985A> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff4c667000 -     0x7fff4c667fff  com.apple.CoreServices (822.31 - 822.31) <615919A2-AE11-3F27-9A37-FB0CFF8D36B6> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff4d64f000 -     0x7fff4da15fff  com.apple.Foundation (6.9 - 1452.23) <E64540AD-1755-3C16-8537-552A00E92541> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff7107f000 -     0x7fff710b2ff7  libclosured.dylib (551.3) <DC3DA678-9C40-339C-A9C6-32AB74FCC682> /usr/lib/closure/libclosured.dylib
    0x7fff715b9000 -     0x7fff715baffb  libSystem.B.dylib (1252.50.4) <C7810EA7-A61F-3817-8E54-E2EC4E26F946> /usr/lib/libSystem.B.dylib
    0x7fff717ee000 -     0x7fff71844fff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff71845000 -     0x7fff71869ff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff72c68000 -     0x7fff730567e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff7372c000 -     0x7fff73730ff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff73731000 -     0x7fff7373bff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff7373c000 -     0x7fff73743fff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff73744000 -     0x7fff7374dffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff7374e000 -     0x7fff737d3fff  libcorecrypto.dylib (562.50.17) <67007279-24E1-3F30-802D-A55CD5C27946> /usr/lib/system/libcorecrypto.dylib
    0x7fff7385b000 -     0x7fff73894ff7  libdispatch.dylib (913.50.12) <848EEE57-4235-3A61-9A52-C0097DD2AB5E> /usr/lib/system/libdispatch.dylib
    0x7fff73895000 -     0x7fff738b2ff7  libdyld.dylib (551.3) <CF59A5A5-288B-30E6-BD42-9056B4E4139A> /usr/lib/system/libdyld.dylib
    0x7fff738b3000 -     0x7fff738b3ffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff738c1000 -     0x7fff738c1ff7  liblaunch.dylib (1205.50.76) <4D52BB64-C568-3A36-8935-2480427EE2A2> /usr/lib/system/liblaunch.dylib
    0x7fff738c2000 -     0x7fff738c6ffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff738c7000 -     0x7fff738c9ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff738ca000 -     0x7fff738cbff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff738cc000 -     0x7fff738e3fff  libsystem_asl.dylib (356.50.1) <3B24F2D1-B578-359D-ADB2-0ED19A364C38> /usr/lib/system/libsystem_asl.dylib
    0x7fff738e4000 -     0x7fff738e4fff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff738e5000 -     0x7fff7396eff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff7396f000 -     0x7fff73972ffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff73973000 -     0x7fff73976ffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff73977000 -     0x7fff73978fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff73979000 -     0x7fff7397fff7  libsystem_dnssd.dylib (878.50.17) <9033B909-BCF7-37EB-A040-ADE8081611D6> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff73980000 -     0x7fff739c9ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff739ca000 -     0x7fff739f0ff7  libsystem_kernel.dylib (4570.51.1) <5CAAB092-02CC-3A37-9D5F-C4AD1083AB96> /usr/lib/system/libsystem_kernel.dylib
    0x7fff739f1000 -     0x7fff73a3cfcb  libsystem_m.dylib (3147.50.1) <FC2E58BA-E6D5-3D2A-89CA-67F212294136> /usr/lib/system/libsystem_m.dylib
    0x7fff73a3d000 -     0x7fff73a5cfff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff73a5d000 -     0x7fff73b8dff3  libsystem_network.dylib (1229.51.2) <F65ED095-8ABA-3355-93F8-B9D0505932F4> /usr/lib/system/libsystem_network.dylib
    0x7fff73b8e000 -     0x7fff73b98ffb  libsystem_networkextension.dylib (767.50.25) <758F1414-796D-3422-83C9-92D2915A06CE> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff73b99000 -     0x7fff73ba2ff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff73ba3000 -     0x7fff73baaff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff73bab000 -     0x7fff73bb6fff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff73bb7000 -     0x7fff73bbafff  libsystem_sandbox.dylib (765.50.51) <B48D256E-D7DB-3D4F-BC95-34557170C7AA> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff73bbb000 -     0x7fff73bbcff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff73bbd000 -     0x7fff73bc4ff7  libsystem_symptoms.dylib (820.50.37) <ED7350E0-B68B-374A-9AB7-DC1F195A8327> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff73bc5000 -     0x7fff73bd8fff  libsystem_trace.dylib (829.50.17) <6568D68B-1D4C-38EE-90A9-54821D6403C0> /usr/lib/system/libsystem_trace.dylib
    0x7fff73bda000 -     0x7fff73bdfff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff73be0000 -     0x7fff73c0dfff  libxpc.dylib (1205.50.76) <25DB244E-217D-3CE0-A8F2-0C4255783B42> /usr/lib/system/libxpc.dylib

Model: MacBookAir6,2, BootROM MBA61.0106.B00, 2 processors, Intel Core i7, 1,7 GHz, 8 GB, SMC 2.13f15
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.37.29.1a7)
Bluetooth: Version 6.0.5f3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SD0128F, 121,33 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Receiver
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6

**Comment by Yoyae** [comment]
We moved to a new repository. In addition, there is a fresh compilation of the new version. You can test this out here : https://github.com/monacocoin-net/monoeci-core/releases/tag/v0.12.2.3

I'm closing the issue here. Feel free to open the issue on the new repository if it still doesn't work.
